services:

  server:
    image: invoiceninja/invoiceninja-debian:${TAG:-latest}
    container_name: ninja-app-wan
    restart: unless-stopped
    env_file: .env
    volumes:
      - storage_data:/var/www/html/storage
      - public_data:/var/www/html/public
    # depends_on:
    #   db:
    #     condition: service_healthy
    #   redis:
    #     condition: service_healthy

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - public_data:/var/www/html/public:ro
      - storage_data:/var/www/html/storage:ro
    # depends_on:
    #   server:
    #     condition: service_healthy

  db:
    image: mariadb:11.8 # 10.5+ is recommended for Invoice Ninja v5
    container_name: ninja-db-wan
    restart: unless-stopped
    env_file: .env
    volumes:
      - mysql_data_mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u$${MYSQL_USER} -p$${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: ninja-redis-wan
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

volumes:
  storage_data:
  public_data:
  mysql_data_mariadb: